"""Shared configuration values for training and inference."""

MAX_WORDS = 20_000
MAX_LEN = 300
OOV_TOKEN = "<OOV>"

EMBEDDING_DIM = 100
LSTM_UNITS = 128
DENSE_UNITS = 64
SPATIAL_DROPOUT_RATE = 0.2
DENSE_DROPOUT_RATE = 0.4

TEST_SIZE = 0.2
RANDOM_STATE = 42
VALIDATION_SPLIT = 0.1
EPOCHS = 10
BATCH_SIZE = 128
EARLY_STOPPING_PATIENCE = 2
LR_REDUCTION_PATIENCE = 1
LR_REDUCTION_FACTOR = 0.5
MIN_LEARNING_RATE = 1e-5

PREDICTION_THRESHOLD = 0.5
